

const events = {
    DISCONNECT: 'disconnect',
    GET_MESSAGES: 'GET_MESSAGES',
    OFFLINE_MESSAGES: 'OFFLINE_MESSAGES',
    ONLINE_USERS: 'ONLINE_USERS',
    SINGLE_CHAT_MESSAGE : 'SINGLE_CHAT_MESSAGE',
    SINGLE_CHAT_MESSAGE_DELIVERED : 'SINGLE_CHAT_MESSAGE_DELIVERED',
    SINGLE_CHAT_MESSAGE_READ : 'SINGLE_CHAT_MESSAGE_READ'
};

module.exports = events;